// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort():Promise<void>;

export function Browse():Promise<string>;

export function BrowseFiles():Promise<Array<string>>;

export function Convert(arg1:Array<string>,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function Scan(arg1:string,arg2:boolean):Promise<string>;

export function ScanFiles(arg1:Array<string>):Promise<string>;
