// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['main']['App']['Abort']();
}

export function AbortNow() {
  return window['go']['main']['App']['AbortNow']();
}

export function AbortScan() {
  return window['go']['main']['App']['AbortScan']();
}

export function Browse() {
  return window['go']['main']['App']['Browse']();
}

export function BrowseFiles() {
  return window['go']['main']['App']['BrowseFiles']();
}

export function Convert(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Convert'](arg1, arg2, arg3, arg4);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function Scan(arg1, arg2) {
  return window['go']['main']['App']['Scan'](arg1, arg2);
}

export function ScanFiles(arg1) {
  return window['go']['main']['App']['ScanFiles'](arg1);
}
